# Generated by Django 3.2.16 on 2022-10-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('short_bio', models.CharField(max_length=500)),
                ('long_bio', models.TextField()),
                ('advocate_years_exp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='')),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdvocateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('advocate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.advocate')),
            ],
        ),
        migrations.AddField(
            model_name='advocate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advocates', to='api.company'),
        ),
    ]
