# Generated by Django 3.2.16 on 2022-10-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocatelink',
            name='advocate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.advocate'),
        ),
    ]
